spring.application.name=TAEM
server.port=8080
spring.web.error.whitelabel.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/taemdb
spring.datasource.username=admin
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#create for testing, it will change after development